services:
  - type: web
    name: impulsorep-web
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_SSL
        value: true
      - key: DATABASE_INIT
        value: true
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
